### ISSUE TITLE
Spells that refuse to work

### ISSUE THREAD

**Issue by Rukbat16** [rtakehara/5e-Framework#3] opened 2020-05-20 21:53 UTC
In version 2.4 I cannot seem to be able to open spell links from the character sheet; however this is a minor annoyance because they mostly work fine from the stat block and the spellcasting sheet.

Also spells tend to end up broken if added from the class spell lists. Searching for them in the search menu and adding them from there seems to work better, for whatever reason.

However, one spell so far has proven stubborn and refuses to work: the cantrip Toll the Dead. (there might be more, I did not test them all - simply the ones I chose for the PCs I made)
Here is the JSON:
{"toll the dead":{"description":"*necromancy cantrip*  \n **Casting time:** 1 Action  \n**Range:** 60 feet  \n**Duration:** Instantaneous  \n**Components:** V, S\n\n---\n\n You point at one creature you can see within range, and the sound of a dolorous bell fills the air around it for a moment. The target must succeed on a Wisdom saving throw or take [1d8](roll \"1d8\") necrotic damage. If the target is missing any of its hit points, it instead takes 1d12 necrotic damage. The spell’s damage increases by one die when you reach 5th level ([2d8](roll \"2d8\") or [2d12](roll \"2d12\")), 11th level ([3d8](roll \"3d8\") or [3d12](roll \"3d12\")), and 17th level ([4d8](roll \"4d8\") or [4d12](roll \"4d12\")).","sources":["XGE"]}}

I chose it as the wizard cantrip for a high elf character. However, no matter how many times I add it to the character, it ends up in the missing or broken part of the spellcasting sheet.

I have tried pasting the text in again from the Edit button on the frame opened by the "broken or missing" link in the spellcasting sheet, but to no avail.
The tooltip opens, with all the text displayed correctly. I can roll the dice from the links within.
But the spell is never "fixed" and is not added to the list of cantrips or the stat block, and if I open the Edit form, the text field in there is blank.

In fact when I first made the character and I tried adding the spell 5-6 times (from various menus) it ended up corrupting the entire character sheet which then would not open and I had to remake the character entirely.

Workaround: I can put a link to the spell in the token's Notes, since they are shown on the stat block, and because the tooltip opens, I can use it from there.

**Comment by thagrasshoppa** [comment] 2020-05-20 22:54
I would love to have a session where we looked at some of the issues you have seen to see if I have them as well, to eliminate your setup or simple mistakes.

**Comment by Rukbat16** [comment] 2020-05-21 18:06
I have detailed the issue quite thoroughly here. Have you created this cantrip, and assigned it successfully to a PC?

**Comment by rtakehara** [comment] 2020-05-23 06:51
Im investigating that. Also, if you add the spell from other sources like the search it seems to go to the right place, so the problem is on creating a new one

**Comment by rtakehara** [comment] 2020-05-24 01:52
fixed on version 2.4.3

**Closed by rtakehara** 2020-05-24 01:52 UTC
